In [1]:
import pandas as pd 
import seaborn as sns

In [2]:
titanic = sns.load_dataset('titanic')
titanic.shape
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [4]:
titanic = titanic(['survived','pclass','sex','age'])

TypeError: 'DataFrame' object is not callable

In [5]:
titanic = titanic(['survived','pclass','sex','age'])

TypeError: 'DataFrame' object is not callable

In [6]:
titanic = titanic[['survived','pclass','sex','age']]

In [7]:
titanic.head()

survived  pclass     sex   age
0         0       3    male  22.0
1         1       1  female  38.0
2         1       3  female  26.0
3         1       1  female  35.0
4         0       3    male  35.0

In [8]:
titanic.dropna(axis=0,inplace=True)
titanic['sex'].replace(['male','female'],[0,1],inplace=True)
titanic.head()

survived  pclass  sex   age
0         0       3    0  22.0
1         1       1    1  38.0
2         1       3    1  26.0
3         1       1    1  35.0
4         0       3    0  35.0

In [9]:
print(titanic.shape)

(714, 4)


In [32]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()

In [33]:
y = titanic['survived']
X = titanic.drop('survived')
model.fit(X,y)
model.score(X,y)
model.predict(X)

KeyError: "['survived'] not found in axis"

In [34]:
y = titanic['survived']
X = titanic.drop('survived',axis=1)


In [35]:
y


0      0
1      1
2      1
3      1
4      0
      ..
885    0
886    0
887    1
889    1
890    0
Name: survived, Length: 714, dtype: int64

In [36]:
X


pclass  sex   age
0         3    0  22.0
1         1    1  38.0
2         3    1  26.0
3         1    1  35.0
4         3    0  35.0
..      ...  ...   ...
885       3    1  39.0
886       2    0  27.0
887       1    1  19.0
889       1    0  26.0
890       3    0  32.0

[714 rows x 3 columns]

In [37]:
model.fit(X,y)
model.score(X,y)
model.predict(X)

array([0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,

In [38]:
model.score(X,y)

0.8417366946778712

In [39]:
from sklearn.metrics import ConfusionMatrixDisplay

In [40]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [41]:
confusion_matrix(y, model.predict, labels=['0','1'])

InvalidParameterError: The 'y_pred' parameter of confusion_matrix must be an array-like. Got <bound method KNeighborsClassifier.predict of KNeighborsClassifier()> instead.

In [42]:
def vivant(mdel, pclass, sex, age)

SyntaxError: expected ':' (2331540748.py, line 1)

In [43]:
def vivant(model, pclass, sex, age):
    X=np.array([pclass, sex, age]).reshape(1, 3)
    print(model.predict(X))
    print(model.predict_proba(X))

In [44]:
vivant(model,3,0,20)

[0]
[[1. 0.]]


C:\Users\hugoh\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
C:\Users\hugoh\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [45]:
import numpy as np


In [46]:
vivant(model,3,0,20)

[0]
[[1. 0.]]


C:\Users\hugoh\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
C:\Users\hugoh\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
